### ISSUE TITLE
Can't load config

### ISSUE THREAD

**Issue by muratsat** [Insality/defold-proto#1]
Hello

I followed example on a new blank project and can't get it to work properly.

If I am doing something incorrectly, could you point out what am I doing wrong? Here's the repo: https://github.com/muratsat/defold-proto-example

When I use `proto.init("/resources/proto.json")`, there's an error:

```
DEBUG:SCRIPT: ERROR: Can't load config,
```

So I tried to pass a lua table directly: 
```
	proto.init({
		["/resources/proto"] = {
			"game.proto"
		}
	})
```

Which also result in error:

```
DEBUG:SCRIPT: DEBUG: Load protofile,
/resources/proto/game.proto
ERROR:SCRIPT: proto/protoc.lua:297: module load error: /game.proto
	Failed to load resource: /game.proto (-3)
	Failed to load resource: /resources/proto/game.proto (-3)
stack traceback:
  [C]:-1: in function error
  proto/protoc.lua:297: in function f
  proto/protoc.lua:1037: in function do_compile
  proto/protoc.lua:1051: in function compilefile
  proto/protoc.lua:1062: in function loadfile
  proto/proto_internal.lua:67: in function load_config
  proto/proto.lua:23: in function init
  main/main.gui_script:10: in function <main/main.gui_script:3>
```

**Comment by Insality** [comment]
Hello! Seems the issue that `custom resources` is not set im `game.project` and Defold Engine can't load them

Your game.project should contains and will look like this:

```init
[project]
custom_resources = /resources
```

From README:
>The module uses sys.load_resource to load the files. Place your files inside your [custom resources folder](https://defold.com/manuals/project-settings/#custom-resources) to ensure they are included in the build.

Will think how to write this section better, thanks

**Comment by muratsat** [comment]
Thank you

That worked for me

**Comment by Insality** [comment]
Cool! Glad it helps
